/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2025-11-29T09:05:12.927153+00:00
/// Collection: mdi-light
/// This is a partial import from Iconify
/// Browse icons: https://icon-sets.iconify.design/mdi-light/
///
/// ```yaml
/// name: Material Design Light
/// author:
///   name: Pictogrammers
///   url: https://github.com/Templarian/MaterialDesignLight
/// license:
///   title: Open Font License
///   spdx: OFL-1.1
///   url: https://github.com/Templarian/MaterialDesignLight/blob/master/LICENSE.md
/// total: 284
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const ClipboardText: IconData = IconData {
    name: "mdi-light:clipboard-text",
    body: r#"<path fill="currentColor" d="M6 5h2.5a3 3 0 0 1 3-3a3 3 0 0 1 3 3H17a3 3 0 0 1 3 3v11a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3m0 1a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-1v3H7V6zm2 2h7V6H8zm3.5-5a2 2 0 0 0-2 2h4a2 2 0 0 0-2-2M6 11h11v1H6zm0 3h11v1H6zm0 3h9v1H6z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Delete: IconData = IconData {
    name: "mdi-light:delete",
    body: r#"<path fill="currentColor" d="M18 19a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3V7H4V4h4.5l1-1h4l1 1H19v3h-1zM6 7v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2V7zm12-1V5h-4l-1-1h-3L9 5H5v1zM8 9h1v10H8zm6 0h1v10h-1z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
